name: Spring Boot Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'correto'

      - name: test
        run: mvn -B test  --file pom.xml
      - name: Build
        run: mvn clean -B package  --file pom.xml
